Repository grackle-project/grackle, pull requests merged in 2023-05, with the labels that each got.

#151 Update pygrackle version to 1.0.0 and add metadata.
  src/python/pygrackle/__init__.py
  src/python/setup.py
Labels: infrastructure

#152 Update branch name references from master to main
  .circleci/config.yml
  .gitmodules
  CONTRIBUTING.rst
  README.md
Labels: infrastructure

#155 Add warning about self-shielding cooling tables.
  doc/source/Parameters.rst
Labels: documentation

#157 Bugfix: making inline legacy internal grackle functions work in C codes
  src/clib/grackle.h
Labels: bug

#158 Update changelog and version for 3.2 release
  CHANGELOG
  doc/source/conf.py
  src/clib/Make.config.assemble
Labels: infrastructure
