Repository grackle-project/grackle, pull requests merged in 2023-07, with the labels that each got.

#163 initializing local_free_chemistry_data
  src/clib/initialize_chemistry_data.c
Labels: bug

#164 Update version and changelog for 3.2.1 release.
  CHANGELOG
  doc/source/conf.py
  src/clib/Make.config.assemble
Labels: releases

#165 Update to next dev version.
  doc/source/conf.py
  src/clib/Make.config.assemble
Labels: releases

#168 Minor tweaks to `initialize_rates.c` of little importance.
  src/clib/initialize_rates.c
Labels: infrastructure

#166 explicitly initialize all struct members to solve plethora of issues
  src/clib/initialize_UVbackground_data.c
  src/clib/initialize_chemistry_data.c
  src/clib/initialize_cloudy_data.c
Labels: bug

#169 Fix memory leak
  src/clib/initialize_chemistry_data.c
Labels: bug

#167 Refactor the `cloudy_data` struct so that the `grid_{dimension,parameters}` members are fixed-size arrays
  src/clib/grackle_chemistry_data.h
  src/clib/initialize_cloudy_data.c
Labels: refactor
