Repository grackle-project/grackle, pull requests merged in 2024-06, with the labels that each got.

#188 Moved public headers into a separate directory.
  src/clib/Make.config.assemble
  src/clib/Makefile
  src/clib/README.md
  src/include/grackle.def
  src/include/grackle.h
  src/include/grackle_chemistry_data.h
  src/include/grackle_float.h.in
  src/include/grackle_fortran_interface.def
  src/include/grackle_fortran_types.def
  src/include/grackle_rate_functions.h
  src/include/grackle_types.h
  src/python/setup.py
  src/python/tests/test_chemistry_struct_synched.py
Labels: refactor

#199 Dropped req for specifying `extern "C"` in C++ apps
  doc/source/Integration.rst
  src/example/cxx_example.C
  src/example/cxx_grid_example.C
  src/example/cxx_omp_example.C
  src/include/grackle.h
  src/include/grackle_chemistry_data.h
  src/include/grackle_rate_functions.h
  src/include/grackle_types.h
Labels: enhancement

#200 Updating behavior of `HydrogenFractionByMass` parameter
  doc/source/Parameters.rst
  src/clib/grackle_chemistry_data_fields.def
  src/clib/initialize_chemistry_data.c
Labels: enhancement, minor

#213 Allow unsupported simulation types to work with grackle yt fields.
  src/python/pygrackle/yt_fields.py
Labels: enhancement

#205 Introduce `gr_initialize_field_data`
  doc/source/Integration.rst
  doc/source/Reference.rst
  src/clib/grackle_field_data_fdatamembers.def
  src/clib/set_default_chemistry_parameters.c
  src/example/c_example.c
  src/example/c_local_example.c
  src/example/cxx_grid_example.C
  src/example/cxx_omp_example.C
  src/example/fortran_example.F
  src/include/grackle.h
  src/include/grackle_fortran_interface.def
  src/python/pygrackle/grackle_defs.pxd
  src/python/pygrackle/grackle_wrapper.pyx
Labels: enhancement
