Repository grackle-project/grackle, pull requests merged in 2024-03, with the labels that each got.

#174 Add mention of c local example to docs.
  doc/source/Integration.rst
Labels: documentation

#180 Fix pygrackle H number density and mean molecular weight calculations
  src/python/pygrackle/fluid_container.py
Labels: bug

#184 Remove deprecated internal functions
  doc/source/Integration.rst
  doc/source/Reference.rst
  src/clib/Make.config.assemble
  src/clib/Makefile
  src/clib/calculate_cooling_time.c
  src/clib/calculate_gamma.c
  src/clib/calculate_pressure.c
  src/clib/calculate_temperature.c
  src/clib/grackle.h
  src/clib/solve_chemistry.c
  src/python/pygrackle/grackle_defs.pxd
Labels: refactor

#179 Make public types refer to named structs
  src/clib/grackle_chemistry_data.h
  src/clib/grackle_types.h
  src/python/tests/test_chemistry_struct_synched.py
Labels: enhancement

#186 Add example to make clean list.
  src/example/Makefile
Labels: build-system
