Repository grackle-project/grackle, pull requests merged in 2025-04, with the labels that each got.

#282 Make `pytest` invokable from the root directory
  .circleci/config.yml
  doc/source/Testing.rst
  pyproject.toml
Labels: documentation, testing

#289 Backport some minor bugfixes
  cmake/AddConditionalFortranFlags.cmake
  src/clib/cool1d_cloudy_old_tables_g.F
  src/clib/initialize_cloudy_data.c
  src/clib/initialize_rates.c
  src/clib/rate_functions.c
  src/example/c_local_example.c
Labels: bug

#279 Add a consistency check for the precision of gr_float
  doc/source/Reference.rst
  src/clib/initialize_chemistry_data.c
  src/example/c_example.c
  src/example/c_local_example.c
  src/example/cxx_example.C
  src/example/cxx_omp_example.C
  src/include/grackle.h
Labels: enhancement

#283 CI: shift core-library tests to a separate "job"
  .circleci/config.yml
  tests/CMakeLists.txt
  tests/scripts/code_example_checker.py
Labels: ci

#295 2 minor (but important) googletest-related CMake tweaks
  cmake/setup_GTest.cmake
Labels: trivial, build-system

#302 tests: gracefully handle `yt_grackle` test-case when `YT_DATA_DIR` isn't defined
  src/python/examples/yt_grackle.py
  src/python/tests/test_models.py
Labels: testing

#293 Updating the README
  README.md
  doc/source/index.rst
Labels: documentation

#297 Introduce a warning discouraging people from using ``pygrackle.utilities.data_path.grackle_data_dir`` in external code
  doc/source/Python.rst
Labels: documentation
