Repository grackle-project/grackle, pull requests merged in 2025-03, with the labels that each got.

#266 Move parameter to correct place in fortran interface.
  src/include/grackle_fortran_interface.def
Labels: bug

#254 Convert `cxx_grid_example` to a googletest test-case
  src/example/CMakeLists.txt
  src/example/Make.config.targets
  src/example/Makefile
  src/python/tests/test_code_examples.py
  tests/unit/CMakeLists.txt
  tests/unit/grtest_utils.cpp
  tests/unit/grtest_utils.hpp
  tests/unit/test_ghost_zone.cpp
Labels: testing

#258 Tweaking code example tests
  .circleci/config.yml
  CMakeLists.txt
  cmake/CreateExampleConfigMakefile.cmake
  doc/source/Installation.rst
  src/clib/CMakeLists.txt
  src/example/c_example.c
  src/example/c_local_example.c
  src/example/cxx_example.C
  src/example/fortran_example.F
  src/python/tests/test_code_examples.py
  tests/CMakeLists.txt
  tests/README.rst
  tests/scripts/c_example_ref.json
  tests/scripts/code_example_checker.py
Labels: bug, testing
