Repository grackle-project/grackle, pull requests merged in 2025-05, with the labels that each got.

#304 Deprecate classic build system
  doc/source/Installation.rst
Labels: documentation, build-system

#310 Address Less Common CMake Configuration Issues
  CMakeLists.txt
  doc/source/Installation.rst
  src/example/CMakeLists.txt
  tests/CMakeLists.txt
Labels: documentation, build-system

#308 Circleci simplifications forgotten in PR #298
  .circleci/config.yml
Labels: trivial, ci

#311 `src/example/Makefile` cleanup
  src/example/Make.config.targets
  src/example/Makefile.out-of-source
Labels: minor

#330 [CRITICAL BUGFIX] Fix a significant oversight in **GrackleConfig.cmake**
  cmake/GrackleConfig.cmake.in
Labels: bug, build-system

#338 Optimize circleci workflows
  .circleci/config.yml
  CMakeLists.txt
  src/example/CMakeLists.txt
Labels: build-system, ci

#337 remove 2 unneeded files
  src/Makefile
  src/python/Makefile
Labels: trivial

#335 Support running subset of pygrackle test without a an editable install
  src/python/pygrackle/utilities/model_tests.py
  src/python/tests/test_models.py
  src/python/tests/testing_common.py
Labels: trivial, testing, python

#329 remove a line that was made obsolete by PR #224
  src/python/CMakeLists.txt
Labels: trivial, build-system, python

#319 cython does not need to be a runtime-dependency
  pyproject.toml
Labels: trivial, python

#309 Pygrackle test instruction tweaks
  doc/source/Testing.rst
  doc/source/testing_snippets/generate.rst
Labels: documentation

#326 fix a typo in a CMake variable name
  CMakeLists.txt
  cmake/installation_rules.cmake
  src/clib/CMakeLists.txt
Labels: trivial, build-system

#328 Tweak cython-handling in build-system
  pyproject.toml
  src/python/CMakeLists.txt
Labels: build-system, python

#325 H2 self shielding length scale factor fix
  src/clib/solve_rate_cool_g.F
Labels: bug

#285 Superficial Website Documentation Tweaks
  .gitignore
  CITATION
  CITATION.rst
  doc/source/Changelog.rst
  doc/source/Citing.rst
  doc/source/index.rst
Labels: documentation

#340 Fix spacing issues in docs.
  doc/source/Parameters.rst
Labels: trivial, documentation

#296 Relocated all CMake-dependency-information into dependencies.cmake
  CMakeLists.txt
  cmake/setup_GTest.cmake
  dependencies.cmake
Labels: build-system

#342 Use builtin GitHub feature to nicely redirect to Code of Conduct
  .github/CODE_OF_CONDUCT.md
Labels: trivial

#300 Simplify GitHub hyperlinks for repository locations in docs
  doc/source/Installation.rst
  doc/source/Interaction.rst
  doc/source/Python.rst
  doc/source/conf.py
Labels: documentation

#291 This patch tries switching the theme to 'furo'
  .circleci/config.yml
  doc/source/conf.py
  doc/source/requirements.txt
  pyproject.toml
Labels: documentation

#346 Remove spurious indentations (fix rendering of text)
  doc/source/Contributing.rst
  doc/source/Installation.rst
  doc/source/Integration.rst
  doc/source/Interaction.rst
  doc/source/Parameters.rst
  doc/source/Python.rst
  doc/source/Reference.rst
  doc/source/Testing.rst
  doc/source/Versioning.rst
Labels: documentation
